GET http://localhost:3000/ HTTP/1.1

###

GET http://localhost:3000/abc HTTP/1.1

###
#you can chose the content type of the body in the request
#this below is the body to send in the request packet
#remember to use always double-quote "" in JSON

POST http://localhost:3000/add/4 HTTP/1.1
Content-Type: application/json

{ "id": 3, "name": "abc" }

###

GET http://localhost:3000/info HTTP/1.1
